name: "yolov8_custom_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 4

input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NONE
    dims: [640, 640, 3]
  }
]

output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [8400, 80]
  },
  {
    name: "bboxes"
    data_type: TYPE_FP32
    dims: [8400, 4]
  }
]
